
-- ==========================================
-- CHED GLOBAL LINKAGE MATRIX - MASTER SCHEMA
-- Version: 2.6.0
-- Security: RLS Enabled (Data Privacy Act 2012)
-- Optimization: pg_trgm for Fuzzy Search
-- ==========================================

-- Enable Trigram Search for fuzzy institutional matching
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- 1. Create Linkages Table
CREATE TABLE IF NOT EXISTS public.linkages (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ DEFAULT now(),
    
    -- Exact Column Mapping for CHED Central Office
    "NAME OF PHEI" TEXT NOT NULL,
    "Type" TEXT NOT NULL, -- SUC, LUC, HEI
    "Region" TEXT NOT NULL,
    "COUNTRY" TEXT NOT NULL,
    "Continent" TEXT NOT NULL,
    "NAME OF FOREIGN INSTITUTION /ORGANIZATION" TEXT NOT NULL,
    "Type of Foreign Partner" TEXT NOT NULL,
    "Field" TEXT, -- Primary cooperated field
    "YEAR SIGNED" INTEGER NOT NULL,
    "DATE SIGNED" DATE,
    "Type of Agreement" TEXT NOT NULL, -- MOU, MOA
    
    -- Verification & Evidence Infrastructure
    -- UPDATED: Added Rejected and Expired to allowed statuses
    verification_status TEXT DEFAULT 'Pending' CHECK (verification_status IN ('Pending', 'Approved', 'Needs Revision', 'Rejected', 'Expired')),
    agreement_path TEXT, -- Storage path for MOU/MOA PDF
    cmo1_path TEXT, -- Storage path for CMO 1 PDF
    REMARKS TEXT, -- Official IAS Directives
    
    -- Strategic Metadata
    sdgs INTEGER[] DEFAULT '{}', -- Array of UN SDG IDs (1-17)
    achieve_categories TEXT[] DEFAULT '{}', -- Array of ACHIEVE Area names
    
    -- Ownership & Security
    registered_by UUID REFERENCES auth.users(id) NOT NULL
);

-- 2. Create High-Performance Search Indexes
CREATE INDEX IF NOT EXISTS idx_linkages_fhei_trgm ON public.linkages USING gin ("NAME OF FOREIGN INSTITUTION /ORGANIZATION" gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_linkages_field_trgm ON public.linkages USING gin ("Field" gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_linkages_country_trgm ON public.linkages USING gin ("COUNTRY" gin_trgm_ops);

-- 3. Create Audit Trail (Comments)
CREATE TABLE IF NOT EXISTS public.partnership_comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    partnership_id UUID REFERENCES public.linkages(id) ON DELETE CASCADE,
    user_id UUID REFERENCES auth.users(id),
    author_name TEXT NOT NULL,
    author_role TEXT NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 4. Create Real-time Notification System
CREATE TABLE IF NOT EXISTS public.notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message TEXT NOT NULL,
    status TEXT DEFAULT 'unread',
    type TEXT DEFAULT 'linkage_submission',
    phei_name TEXT,
    linkage_id UUID REFERENCES public.linkages(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 5. Saved benchmarks (Updated table name from 'favorites' to 'benchmarks' to match code)
CREATE TABLE IF NOT EXISTS public.benchmarks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    linkage_id UUID REFERENCES public.linkages(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT now(),
    UNIQUE(user_id, linkage_id)
);

-- ==========================================
-- SECURITY POLICIES (RLS)
-- ==========================================

ALTER TABLE public.linkages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.partnership_comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.benchmarks ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for all authenticated users" 
ON public.linkages FOR SELECT TO authenticated USING (true);

CREATE POLICY "Users can insert their own linkages" 
ON public.linkages FOR INSERT TO authenticated 
WITH CHECK (auth.uid() = registered_by);

CREATE POLICY "Admins can update status or anyone can update own pending record"
ON public.linkages FOR UPDATE TO authenticated
USING (
  (auth.jwt() -> 'user_metadata' ->> 'role') = 'CHED_ADMIN' OR
  (auth.uid() = registered_by AND verification_status = 'Needs Revision')
);

CREATE POLICY "Comments are viewable by participants" 
ON public.partnership_comments FOR SELECT TO authenticated USING (true);

CREATE POLICY "Participants can post comments" 
ON public.partnership_comments FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Admins can manage notifications" 
ON public.notifications FOR ALL TO authenticated 
USING ((auth.jwt() -> 'user_metadata' ->> 'role') = 'CHED_ADMIN');

CREATE POLICY "Users can manage their benchmarks"
ON public.benchmarks FOR ALL TO authenticated
USING (auth.uid() = user_id);

ALTER PUBLICATION supabase_realtime ADD TABLE public.notifications;
ALTER PUBLICATION supabase_realtime ADD TABLE public.linkages;
